name: 'DataBoySu Readme Translator'
description: 'Automatically translates your README.md into multiple languages.'
author: 'DataBoySu'
branding:
  icon: 'globe'
  color: 'green'

inputs:
  lang:
    description: 'Target language code (e.g., fr, de, ja, es)'
    required: false
  readme_path:
    description: 'Path to the README file to translate (relative to repo root)'
    default: 'README.md'
    required: false
  model_url:
    description: 'URL to download the GGUF model'
    # default: 'https://huggingface.co/lmstudio-community/aya-expanse-8b-GGUF/resolve/main/aya-expanse-8b-Q4_K_M.gguf'
    default: 'https://huggingface.co/lmstudio-community/Qwen3-14B-GGUF/resolve/main/Qwen3-14B-Q4_K_M.gguf'
    required: false
  model_cache_path:
    description: 'Path to cache the model (internal)'
    default: '.cache/models'
    required: false
  mode:
    description: 'Operation mode: translate (default) or navbar'
    default: 'translate'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Translator Model
      id: cache-model
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/${{ inputs.model_cache_path }}
        # key: translator-model-aya-expanse-8b-v1
        key: translator-model-qwen3-14b-q4km-v1

    - name: Run Entrypoint
      shell: bash
      env:
        MODEL_CACHE_DIR: ${{ github.workspace }}/${{ inputs.model_cache_path }}
      run: |
        # We execute the entrypoint script located in the action's path
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh "${{ inputs.lang }}" "${{ inputs.readme_path }}" "${{ inputs.model_url }}" "${{ inputs.mode }}"
