name: 'DataBoySu Readme Translator'
description: 'Composite GitHub Action to translate README files and append a language navbar.'
author: 'DataBoySu'
branding:
  icon: globe
  color: blue

inputs:
  lang:
    description: 'Target language code (e.g., de, fr). Use "all" to run all locales.'
    required: false
    default: 'de'
  model_path:
    description: 'Local path to GGUF model on the runner (optional).'
    required: false
    default: ''
  nav_target:
    description: 'README file to update (path relative to repo root).'
    required: false
    default: 'README.md'
  dry_run:
    description: 'If true, do not commit changes; just write outputs to workspace.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r readme-translator-action/requirements.txt

    - name: Run translator (entrypoint)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_LANG: ${{ inputs.lang }}
        INPUT_MODEL_PATH: ${{ inputs.model_path }}
        INPUT_MODEL_URL: ${{ inputs.model_url }}
        INPUT_NAV_TARGET: ${{ inputs.nav_target }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
      run: |
        chmod +x readme-translator-action/entrypoint.sh
        ./readme-translator-action/entrypoint.sh
