name: 'DataBoySu Readme Translator'
description: 'Composite GitHub Action to translate README files and append a language navbar.'
author: 'DataBoySu'
branding:
  icon: globe
  color: blue

inputs:
  lang:
    description: 'Target language code (e.g., de, fr). Use "all" to run all locales.'
    required: false
    default: 'de'
  model_path:
    description: 'Local path to GGUF model on the runner (optional).'
    required: false
    default: ''
  model_url:
    description: 'Optional URL to download GGUF model into the runner cache.'
    required: false
    default: ''
  token_name:
    description: 'Name of the secret that stores a write-capable GitHub token (e.g. GH_TOKEN).'
    required: false
    default: 'GH_TOKEN'
  nav_target:
    description: 'README file to update (path relative to repo root).'
    required: false
    default: 'README.md'
  commit:
    description: 'If true, commit and push README changes back to the repo (requires permissions).'
    required: false
    default: 'false'
  commit_message:
    description: 'Commit message to use when committing README changes.'
    required: false
    default: 'Update README translations'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "$GITHUB_ACTION_PATH/requirements.txt"

    - name: Run translator (entrypoint)
      env:
        GITHUB_TOKEN: ${{ secrets[ inputs.token_name ] }}
        INPUT_LANG: ${{ inputs.lang }}
        INPUT_MODEL_PATH: ${{ inputs.model_path }}
        INPUT_MODEL_URL: ${{ inputs.model_url }}
        INPUT_NAV_TARGET: ${{ inputs.nav_target }}
      run: |
        chmod +x "$GITHUB_ACTION_PATH/entrypoint.sh"
        "$GITHUB_ACTION_PATH/entrypoint.sh"

    - name: Verify token scopes (required for commit)
      if: ${{ inputs.commit == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets[ inputs.token_name ] }}
      run: |
        set -e
        echo "[action] Verifying token scopes via GitHub API"
        headers=$(curl -sI -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/user || true)
        echo "$headers"
        scopes=$(echo "$headers" | tr -d '\r' | awk -F': ' '/^X-OAuth-Scopes/ {print tolower($2)}' || true)
        if [ -z "$scopes" ]; then
          echo "Could not determine token scopes. Ensure the secret is valid." >&2
          exit 1
        fi
        echo "Token scopes: $scopes"
        echo "$scopes" | grep -q "repo" || { echo "Token missing 'repo' scope (or equivalent). Aborting." >&2; exit 1; }

    - name: Commit & push changes
      if: ${{ inputs.commit == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets[ inputs.token_name ] }}
      run: |
        set -e
        git config user.name "readme-translator[bot]"
        git config user.email "readme-translator[bot]@users.noreply.github.com"
        git add "${{ inputs.nav_target }}" || true
        git add locales || true
        # Use token-authenticated remote so push succeeds
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "${{ inputs.commit_message }}"
          git push origin HEAD
        fi
