name: DataBoySu Readme Translator
description: Composite GitHub Action to translate README files and append a language navbar.
author: DataBoySu
branding:
  icon: globe
  color: blue

inputs:
  lang:
    description: 'Target language code (e.g., de, fr). Use "all" to run all locales.'
    required: false
    default: 'de'
  nav_target:
    description: 'README file to update (path relative to repo root).'
    required: false
    default: 'README.md'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r readme-translator-action/requirements.txt

    - name: Verify token scopes (requires write permission)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -z "${GITHUB_TOKEN:-}" ]; then
          echo "GITHUB_TOKEN is not set. Your workflow must provide secrets.GITHUB_TOKEN with write permission.";
          exit 1;
        fi
        echo "Checking token scopes via GitHub API headers..."
        scopes=$(curl -sI -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/ | tr -d '\r' | grep -i '^x-oauth-scopes:' | awk -F: '{print $2}' || true)
        echo "Detected scopes: $scopes"
        if echo "$scopes" | grep -E 'repo|public_repo' >/dev/null; then
          echo "Token appears to include repo/write scopes. Proceeding."
        else
          echo "Token does not appear to include 'repo' or 'public_repo' scopes. Ensure your workflow sets 'permissions: contents: write'."
          exit 1
        fi

    - name: Run translator (entrypoint)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_LANG: ${{ inputs.lang }}
        INPUT_NAV_TARGET: ${{ inputs.nav_target }}
      run: |
        chmod +x readme-translator-action/entrypoint.sh
        ./readme-translator-action/entrypoint.sh

    - name: Commit & push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e
        git config user.name "readme-translator[bot]"
        git config user.email "readme-translator[bot]@users.noreply.github.com"
        git add "${{ inputs.nav_target }}" || true
        git add locales || true
        # Use token-authenticated remote so push succeeds
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update README translations"
          git push origin HEAD
        fi
name: DataBoySu Readme Translator
description: Composite GitHub Action to translate README files and append a language navbar.
author: DataBoySu
branding:
  icon: globe
  color: blue

inputs:
  lang:
    description: 'Target language code (e.g., de, fr). Use "all" to run all locales.'
    required: false
    default: 'de'
  nav_target:
    description: 'README file to update (path relative to repo root).'
    required: false
    default: 'README.md'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r readme-translator-action/requirements.txt

    - name: Verify token scopes (requires write permission)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -z "${GITHUB_TOKEN:-}" ]; then
          echo "GITHUB_TOKEN is not set. Your workflow must provide secrets.GITHUB_TOKEN with write permission.";
          exit 1;
        fi
        echo "Checking token scopes via GitHub API headers..."
        scopes=$(curl -sI -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/ | tr -d '\r' | grep -i '^x-oauth-scopes:' | awk -F: '{print $2}' || true)
        echo "Detected scopes: $scopes"
        if echo "$scopes" | grep -E 'repo|public_repo' >/dev/null; then
          echo "Token appears to include repo/write scopes. Proceeding."
        else
          echo "Token does not appear to include 'repo' or 'public_repo' scopes. Ensure your workflow sets 'permissions: contents: write'."
          exit 1
        fi

    - name: Run translator (entrypoint)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_LANG: ${{ inputs.lang }}
        INPUT_NAV_TARGET: ${{ inputs.nav_target }}
      run: |
        chmod +x readme-translator-action/entrypoint.sh
        ./readme-translator-action/entrypoint.sh

    - name: Commit & push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ inputs.nav_target }}" || true
        git add locales || true
        # Use token-authenticated remote so push succeeds
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update README translations"
          git push origin HEAD
        fi
name: DataBoySu Readme Translator
description: Composite GitHub Action to translate README files and append a language navbar.
author: DataBoySu
branding:
  icon: globe
  color: blue

inputs:
  lang:
    description: 'Target language code (e.g., de, fr). Use "all" to run all locales.'
    required: false
    default: 'de'
  nav_target:
    description: 'README file to update (path relative to repo root).'
    required: false
    default: 'README.md'
  dry_run:
    description: 'If true, do not commit changes; just write outputs to workspace.'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r readme-translator-action/requirements.txt

    - name: Run translator (entrypoint)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_LANG: ${{ inputs.lang }}
        INPUT_NAV_TARGET: ${{ inputs.nav_target }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
      run: |
        chmod +x readme-translator-action/entrypoint.sh
        ./readme-translator-action/entrypoint.sh

    - name: Commit & push changes
      if: ${{ inputs.dry_run != 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ inputs.nav_target }}" || true
        git add locales || true
        # Use token-authenticated remote so push succeeds
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update README translations"
          git push origin HEAD
        fi
name: 'DataBoySu Readme Translator'
description: 'Composite GitHub Action to translate README files and append a language navbar.'
author: 'DataBoySu'
branding:
  icon: globe
  color: blue

inputs:
  lang:
    description: 'Target language code (e.g., de, fr). Use "all" to run all locales.'
    required: false
    default: 'de'
  model_path:
    description: 'Local path to GGUF model on the runner (optional).'
    required: false
    default: ''
  model_url:
    description: 'Optional URL to download GGUF model into the runner cache.'
    required: false
    default: ''
  nav_target:
    description: 'README file to update (path relative to repo root).'
    required: false
    default: 'README.md'
  dry_run:
    description: 'If true, do not commit changes; just write outputs to workspace.'
    required: false
    default: 'false'
  commit:
    description: 'If true, commit and push README changes back to the repo (requires permissions).'
    required: false
    default: 'false'
  commit_message:
    description: 'Commit message to use when committing README changes.'
    required: false
    default: 'Update README translations'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r readme-translator-action/requirements.txt

    - name: Run translator (entrypoint)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_LANG: ${{ inputs.lang }}
        INPUT_MODEL_PATH: ${{ inputs.model_path }}
        INPUT_MODEL_URL: ${{ inputs.model_url }}
        INPUT_NAV_TARGET: ${{ inputs.nav_target }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
      run: |
        chmod +x readme-translator-action/entrypoint.sh
        ./readme-translator-action/entrypoint.sh

    - name: Commit & push changes
      if: ${{ inputs.commit == 'true' && inputs.dry_run != 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ inputs.nav_target }}" || true
        git add locales || true
        # Use token-authenticated remote so push succeeds
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "${{ inputs.commit_message }}"
          git push origin HEAD
        fi
